// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdPXCjZ0ofR9TUrjuPit7CWFotxDiXruE',
    appId: '1:101345066443:web:333417cce6d632ead78a4e',
    messagingSenderId: '101345066443',
    projectId: 'plaid-flutter-b3374',
    authDomain: 'plaid-flutter-b3374.firebaseapp.com',
    storageBucket: 'plaid-flutter-b3374.firebasestorage.app',
    measurementId: 'G-45K2307MVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG2zbzMZwm8BanjJ4LZta6gEEz_YTBZfo',
    appId: '1:101345066443:android:8b10a6d9949d817ed78a4e',
    messagingSenderId: '101345066443',
    projectId: 'plaid-flutter-b3374',
    storageBucket: 'plaid-flutter-b3374.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDDXG6LN1V2Hnim-oMkap317_wrnsN_eE',
    appId: '1:101345066443:ios:fe9f6407d7b890dfd78a4e',
    messagingSenderId: '101345066443',
    projectId: 'plaid-flutter-b3374',
    storageBucket: 'plaid-flutter-b3374.firebasestorage.app',
    iosBundleId: 'com.example.plaidFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDDXG6LN1V2Hnim-oMkap317_wrnsN_eE',
    appId: '1:101345066443:ios:6e002604fa89b04ed78a4e',
    messagingSenderId: '101345066443',
    projectId: 'plaid-flutter-b3374',
    storageBucket: 'plaid-flutter-b3374.firebasestorage.app',
    iosBundleId: 'com.innerlight.personalfinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdPXCjZ0ofR9TUrjuPit7CWFotxDiXruE',
    appId: '1:101345066443:web:43f285f5d2dfe643d78a4e',
    messagingSenderId: '101345066443',
    projectId: 'plaid-flutter-b3374',
    authDomain: 'plaid-flutter-b3374.firebaseapp.com',
    storageBucket: 'plaid-flutter-b3374.firebasestorage.app',
    measurementId: 'G-1T3HTPMZE5',
  );
}
