// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBA6IY_xCuFsllfNU4LA4tvWVfWiMFQRM',
    appId: '1:719770857645:web:e7fc3c7d2123328017d624',
    messagingSenderId: '719770857645',
    projectId: 'flash-chat-3cc2c',
    authDomain: 'flash-chat-3cc2c.firebaseapp.com',
    storageBucket: 'flash-chat-3cc2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmiykMe3qqPU1hNkZdWCB4RmMS9OJ-lc8',
    appId: '1:719770857645:android:ced6e5a8cb1d86c917d624',
    messagingSenderId: '719770857645',
    projectId: 'flash-chat-3cc2c',
    storageBucket: 'flash-chat-3cc2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvuenaJaJbDx28qwgFptdXC8wOoltTnoc',
    appId: '1:719770857645:ios:182e7afbd0ae4b7517d624',
    messagingSenderId: '719770857645',
    projectId: 'flash-chat-3cc2c',
    storageBucket: 'flash-chat-3cc2c.firebasestorage.app',
    iosBundleId: 'com.example.flashCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvuenaJaJbDx28qwgFptdXC8wOoltTnoc',
    appId: '1:719770857645:ios:182e7afbd0ae4b7517d624',
    messagingSenderId: '719770857645',
    projectId: 'flash-chat-3cc2c',
    storageBucket: 'flash-chat-3cc2c.firebasestorage.app',
    iosBundleId: 'com.example.flashCard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBA6IY_xCuFsllfNU4LA4tvWVfWiMFQRM',
    appId: '1:719770857645:web:8e35fe725c50bfe817d624',
    messagingSenderId: '719770857645',
    projectId: 'flash-chat-3cc2c',
    authDomain: 'flash-chat-3cc2c.firebaseapp.com',
    storageBucket: 'flash-chat-3cc2c.firebasestorage.app',
  );

}